spring:
  application:
    name: cloud-ecommerce-api

  datasource:
    url: jdbc:postgresql://localhost:5432/cloud_ecommerce_db
    username: postgres
    password: 123
    driver-class-name: org.hibernate.dialect.PostgreSQLDialect

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true